alias ls="ls --color=auto"
alias l="ls -la"       # List in long format, include dotfiles
alias la="ls -a"
alias ll="ls -l"
alias ld="ls -ld */"   # List in long format, only directories
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..='cd ../'                         

# Make Tab autocomplete regardless of filename case
set completion-ignore-case on
# List all matches in case multiple possible completions are possible
set show-all-if-ambiguous on

export EDITOR="vim"
export CLICOLOR=1
# Tell grep to highlight matches
export GREP_OPTIONS='—color=auto'

# Don't include duplicate lines in history
export HISTCONTROL=ignoredups

